/**
 * Returns an object containing only those keys from `obj` whose value
 * differs from `base`. Works recursively on nested objects.
 *
 * This function has been generated by ChatGPT.
 */
export function getConfigDiff(obj, base) {
    const diff = {}
  
    for (const key in obj) {
        const val = obj[key]
        const def = base[key]

        if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
            const nested = getConfigDiff(val, def || {})
            if (Object.keys(nested).length > 0) {
                diff[key] = nested
            }
        } else {
            const isArray = Array.isArray(val)
            const changed = isArray
                ? JSON.stringify(val) !== JSON.stringify(def)
                : val !== def

            if (changed) {
                diff[key] = val
            }
        }
    }
  
    return diff
}